theme = "catppuccin_mocha"

[editor]
true-color = true
line-number = "relative"
mouse = false
bufferline = "multiple"
auto-save = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

